2017-10-23 00:05:05,646 INFO     [main] [<module>:  47] Starting Script
2017-10-23 00:05:34,531 INFO     [main] [<module>:  48] Starting Script
2017-10-23 00:06:50,713 INFO     [main] [<module>:  48] Starting Script
2017-10-23 00:09:01,407 INFO     [main] [<module>:  48] Starting Script
2017-10-23 00:09:21,546 INFO     [main] [<module>:  48] Starting Script
2017-10-23 00:10:39,920 INFO     [main] [<module>:  48] Starting Script
2017-10-23 00:24:37,007 INFO     [main] [<module>:  47] Starting Script
2017-10-23 00:24:37,009 ERROR    [main] [<module>:  83] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 80, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 41, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 13, in build
    logger.info('Building Chart...')
NameError: name 'logger' is not defined

2017-10-23 00:25:38,620 INFO     [main] [<module>:  47] Starting Script
2017-10-23 00:25:38,622 INFO     [model] [build:  13] Building Chart...
2017-10-23 00:25:38,622 ERROR    [main] [<module>:  83] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 80, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 41, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 15, in build
    self.skeleton = json.loads(open('barchart.json').read())[0]
FileNotFoundError: [Errno 2] No such file or directory: 'barchart.json'

2017-10-23 00:25:48,609 INFO     [main] [<module>:  47] Starting Script
2017-10-23 00:25:48,610 INFO     [model] [build:  13] Building Chart...
2017-10-23 00:25:48,611 ERROR    [main] [<module>:  83] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 80, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 41, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 15, in build
    self.skeleton = json.loads(open('skeletons/barchart.json').read())[0]
KeyError: 0

2017-10-23 00:26:27,561 INFO     [main] [<module>:  47] Starting Script
2017-10-23 00:26:27,563 INFO     [model] [build:  13] Building Chart...
2017-10-23 00:26:27,564 ERROR    [main] [<module>:  83] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 80, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 41, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 15, in build
    self.skeleton = json.loads(open('skeletons/barchart.json').read())[0]
KeyError: 0

2017-10-23 00:26:27,564 INFO     [main] [<module>:  84] Ending Script Unsuccessfully
2017-10-23 00:28:08,365 INFO     [main] [<module>:  47] Starting Script
2017-10-23 00:28:08,367 INFO     [model] [build:  13] Building Chart...
2017-10-23 00:28:08,367 ERROR    [main] [<module>:  83] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 80, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 41, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 16, in build
    skel_content = skel_file.read()
AttributeError: 'str' object has no attribute 'read'

2017-10-23 00:28:08,368 INFO     [main] [<module>:  84] Ending Script Unsuccessfully
2017-10-23 00:28:30,010 INFO     [main] [<module>:  47] Starting Script
2017-10-23 00:28:30,011 INFO     [model] [build:  13] Building Chart...
2017-10-23 00:28:30,012 ERROR    [main] [<module>:  83] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 80, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 41, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 18, in build
    print('Skeleton: ', skeleton)
NameError: name 'skeleton' is not defined

2017-10-23 00:28:30,012 INFO     [main] [<module>:  84] Ending Script Unsuccessfully
2017-10-23 00:28:36,221 INFO     [main] [<module>:  47] Starting Script
2017-10-23 00:28:36,223 INFO     [model] [build:  13] Building Chart...
2017-10-23 00:37:43,035 INFO     [main] [<module>:  47] Starting Script
2017-10-23 00:37:43,037 INFO     [model] [build:  15] Building Chart...
2017-10-23 00:37:43,037 ERROR    [main] [<module>:  83] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 80, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 41, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 24, in build
    self.spec['scales'][0]['domain']['field'] = columns[0]
NameError: name 'columns' is not defined

2017-10-23 00:37:43,038 INFO     [main] [<module>:  84] Ending Script Unsuccessfully
2017-10-23 00:38:10,657 INFO     [main] [<module>:  47] Starting Script
2017-10-23 00:38:10,659 INFO     [model] [build:  15] Building Chart...
2017-10-23 00:38:10,660 ERROR    [main] [<module>:  83] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 80, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 41, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 28, in build
    self.spec['scales'][1]['domain']['field'] = columns[1]
NameError: name 'columns' is not defined

2017-10-23 00:38:10,660 INFO     [main] [<module>:  84] Ending Script Unsuccessfully
2017-10-23 00:38:18,798 INFO     [main] [<module>:  47] Starting Script
2017-10-23 00:38:18,800 INFO     [model] [build:  15] Building Chart...
2017-10-23 00:38:18,801 ERROR    [main] [<module>:  83] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 80, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 41, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 31, in build
    print('Vega Spec: ', spec)
NameError: name 'spec' is not defined

2017-10-23 00:38:18,801 INFO     [main] [<module>:  84] Ending Script Unsuccessfully
2017-10-23 00:38:24,796 INFO     [main] [<module>:  47] Starting Script
2017-10-23 00:38:24,797 INFO     [model] [build:  15] Building Chart...
2017-10-23 00:40:57,573 INFO     [main] [<module>:  48] Starting Script
2017-10-23 00:40:57,574 INFO     [model] [build:  15] Building Chart...
2017-10-23 00:40:57,574 ERROR    [main] [<module>:  84] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 81, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 44, in run
    json.dumps(self.vega_json, vega_spec)
NameError: name 'json' is not defined

2017-10-23 00:40:57,575 INFO     [main] [<module>:  85] Ending Script Unsuccessfully
2017-10-23 00:41:04,976 INFO     [main] [<module>:  49] Starting Script
2017-10-23 00:41:04,977 INFO     [model] [build:  15] Building Chart...
2017-10-23 00:41:04,978 ERROR    [main] [<module>:  85] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 82, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 45, in run
    json.dumps(self.vega_json, vega_spec)
TypeError: dumps() takes 1 positional argument but 2 were given

2017-10-23 00:41:04,978 INFO     [main] [<module>:  86] Ending Script Unsuccessfully
2017-10-23 00:41:45,777 INFO     [main] [<module>:  49] Starting Script
2017-10-23 00:41:45,778 INFO     [model] [build:  15] Building Chart...
2017-10-23 00:54:17,040 INFO     [main] [<module>:  49] Starting Script
2017-10-23 00:54:17,042 INFO     [model] [build:  17] Building Chart...
2017-10-23 00:54:17,043 ERROR    [main] [<module>:  85] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 82, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 42, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 23, in build
    updateNestedDict(self.spec, 'url', self.data_file)
NameError: name 'updateNestedDict' is not defined

2017-10-23 00:54:17,043 INFO     [main] [<module>:  86] Ending Script Unsuccessfully
2017-10-23 00:54:43,470 INFO     [main] [<module>:  49] Starting Script
2017-10-23 00:54:43,471 INFO     [model] [build:  17] Building Chart...
2017-10-23 00:57:06,112 INFO     [main] [<module>:  52] Starting Script
2017-10-23 00:57:06,114 INFO     [model] [build:  17] Building Vega Specification...
2017-10-23 00:57:06,114 INFO     [model] [build:  33] Done Building
2017-10-23 00:57:06,115 ERROR    [main] [<module>:  88] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 85, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 47, in run
    self.logger.info('Vega specification outputted as: ' + output_file)
AttributeError: 'Pipeline' object has no attribute 'logger'

2017-10-23 00:57:06,115 INFO     [main] [<module>:  89] Ending Script Unsuccessfully
2017-10-23 00:57:27,408 INFO     [main] [<module>:  52] Starting Script
2017-10-23 00:57:27,409 INFO     [model] [build:  17] Building Vega Specification...
2017-10-23 00:57:27,410 INFO     [model] [build:  33] Done Building
2017-10-23 00:57:27,410 INFO     [main] [run:  47] Vega specification outputted as: spec.json
2017-10-23 00:58:40,781 INFO     [main] [<module>:  52] Starting Script
2017-10-23 00:58:40,782 INFO     [model] [build:  17] Building Vega Specification...
2017-10-23 00:58:40,783 ERROR    [main] [<module>:  88] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 85, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 42, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 23, in build
    updateNestedDict(self.spec, 'url', self.data_file)
  File "/Users/conder/Desktop/auto_vega/utils.py", line 5, in updateNestedDict
    item = _finditem(v, key, new_val)
NameError: name '_finditem' is not defined

2017-10-23 00:58:40,784 INFO     [main] [<module>:  89] Ending Script Unsuccessfully
2017-10-23 00:58:52,559 INFO     [main] [<module>:  52] Starting Script
2017-10-23 00:58:52,561 INFO     [model] [build:  17] Building Vega Specification...
2017-10-23 00:58:52,562 ERROR    [main] [<module>:  88] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 85, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 42, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 23, in build
    updateNestedDict(self.spec, 'url', self.data_file)
  File "/Users/conder/Desktop/auto_vega/utils.py", line 5, in updateNestedDict
    item = updateNestedDict(v, key, new_val)
  File "/Users/conder/Desktop/auto_vega/utils.py", line 3, in updateNestedDict
    for k, v in obj.items():
AttributeError: 'list' object has no attribute 'items'

2017-10-23 00:58:52,562 INFO     [main] [<module>:  89] Ending Script Unsuccessfully
2017-10-23 01:02:44,930 INFO     [main] [<module>:  52] Starting Script
2017-10-23 01:02:44,932 INFO     [model] [build:  17] Building Vega Specification...
2017-10-23 01:02:44,932 ERROR    [main] [<module>:  88] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 85, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 42, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 23, in build
    updateNestedDict(self.spec, 'url', self.data_file)
  File "/Users/conder/Desktop/auto_vega/utils.py", line 10, in updateNestedDict
    _recurseObj(v, key, new_val)
  File "/Users/conder/Desktop/auto_vega/utils.py", line 17, in _recurseObj
    item = updateNestedDict(obj, key, new_val)
  File "/Users/conder/Desktop/auto_vega/utils.py", line 13, in updateNestedDict
    _recurseObj(v, key, new_val)
UnboundLocalError: local variable 'v' referenced before assignment

2017-10-23 01:02:44,933 INFO     [main] [<module>:  89] Ending Script Unsuccessfully
2017-10-23 01:03:19,929 INFO     [main] [<module>:  52] Starting Script
2017-10-23 01:03:19,931 INFO     [model] [build:  17] Building Vega Specification...
2017-10-23 01:03:19,931 INFO     [model] [build:  33] Done Building
2017-10-23 01:03:19,932 INFO     [main] [run:  47] Vega specification outputted as: spec.json
2017-10-23 01:18:33,835 INFO     [main] [<module>:  52] Starting Script
2017-10-23 01:18:33,836 INFO     [model] [build:  17] Building Vega Specification...
2017-10-23 01:18:33,837 ERROR    [main] [<module>:  88] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 85, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 42, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 23, in build
    updateNestedDictByVal(self.spec, None, self.data_file)
  File "/Users/conder/Desktop/auto_vega/utils.py", line 24, in updateNestedDictByVal
    _recurseObj(v, val, new_val)
NameError: name '_recurseObj' is not defined

2017-10-23 01:18:33,837 INFO     [main] [<module>:  89] Ending Script Unsuccessfully
2017-10-23 01:18:46,822 INFO     [main] [<module>:  52] Starting Script
2017-10-23 01:18:46,823 INFO     [model] [build:  17] Building Vega Specification...
2017-10-23 01:18:46,824 ERROR    [main] [<module>:  88] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 85, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 42, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 23, in build
    updateNestedDictByVal(self.spec, None, self.data_file)
  File "/Users/conder/Desktop/auto_vega/utils.py", line 24, in updateNestedDictByVal
    _recurseObjByVal(v, val, new_val)
  File "/Users/conder/Desktop/auto_vega/utils.py", line 31, in _recurseObjByVal
    key = updateNestedDict(obj, val, new_val)
NameError: name 'updateNestedDict' is not defined

2017-10-23 01:18:46,824 INFO     [main] [<module>:  89] Ending Script Unsuccessfully
2017-10-23 01:18:55,945 INFO     [main] [<module>:  52] Starting Script
2017-10-23 01:18:55,946 INFO     [model] [build:  17] Building Vega Specification...
2017-10-23 01:18:55,947 ERROR    [main] [<module>:  88] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 85, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 42, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 23, in build
    updateNestedDictByVal(self.spec, None, self.data_file)
  File "/Users/conder/Desktop/auto_vega/utils.py", line 24, in updateNestedDictByVal
    _recurseObjByVal(v, val, new_val)
  File "/Users/conder/Desktop/auto_vega/utils.py", line 31, in _recurseObjByVal
    key = updateNestedDictByVal(obj, val, new_val)
  File "/Users/conder/Desktop/auto_vega/utils.py", line 18, in updateNestedDictByVal
    for k, v in obj.items():
AttributeError: 'list' object has no attribute 'items'

2017-10-23 01:18:55,947 INFO     [main] [<module>:  89] Ending Script Unsuccessfully
2017-10-23 01:19:45,588 INFO     [main] [<module>:  52] Starting Script
2017-10-23 01:19:45,589 INFO     [model] [build:  17] Building Vega Specification...
2017-10-23 01:19:45,589 INFO     [model] [build:  33] Done Building
2017-10-23 01:19:45,590 INFO     [main] [run:  47] Vega specification outputted as: spec.json
2017-10-23 01:22:17,877 INFO     [main] [<module>:  52] Starting Script
2017-10-23 01:22:17,878 INFO     [model] [build:  17] Building Vega Specification...
2017-10-23 01:22:17,879 ERROR    [main] [<module>:  88] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 85, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 42, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 26, in build
    updatedNestedDictByVal(self.spec, None, self.columns[0])
NameError: name 'updatedNestedDictByVal' is not defined

2017-10-23 01:22:17,879 INFO     [main] [<module>:  89] Ending Script Unsuccessfully
2017-10-23 01:22:52,706 INFO     [main] [<module>:  52] Starting Script
2017-10-23 01:22:52,708 INFO     [model] [build:  17] Building Vega Specification...
2017-10-23 01:22:52,708 INFO     [model] [build:  38] Done Building
2017-10-23 01:22:52,708 INFO     [main] [run:  47] Vega specification outputted as: spec.json
2017-10-23 01:29:45,653 INFO     [main] [<module>:  52] Starting Script
2017-10-23 01:29:45,655 INFO     [model] [build:  17] Building Vega Specification...
2017-10-23 01:29:45,655 INFO     [model] [build:  38] Done Building
2017-10-23 01:29:45,655 INFO     [main] [run:  47] Vega specification outputted as: spec.json
2017-10-23 01:33:49,124 INFO     [main] [<module>:  52] Starting Script
2017-10-23 01:33:49,125 INFO     [model] [build:  17] Building Vega Specification...
2017-10-23 01:33:49,126 INFO     [model] [build:  38] Done Building
2017-10-23 01:33:49,126 INFO     [main] [run:  47] Vega specification outputted as: spec.json
2017-10-23 01:34:23,047 INFO     [main] [<module>:  52] Starting Script
2017-10-23 01:34:23,049 INFO     [model] [build:  17] Building Vega Specification...
2017-10-23 01:34:23,049 INFO     [model] [build:  38] Done Building
2017-10-23 01:34:23,050 INFO     [main] [run:  47] Vega specification outputted as: spec.json
2017-10-23 01:36:41,137 INFO     [main] [<module>:  52] Starting Script
2017-10-23 01:36:41,138 INFO     [model] [build:  17] Building Vega Specification...
2017-10-23 01:36:41,139 INFO     [model] [build:  38] Done Building
2017-10-23 01:36:41,139 INFO     [main] [run:  47] Vega specification outputted as: spec.json
2017-10-23 01:37:07,138 INFO     [main] [<module>:  52] Starting Script
2017-10-23 01:37:07,139 INFO     [model] [build:  17] Building Vega Specification...
2017-10-23 01:37:07,139 INFO     [model] [build:  38] Done Building
2017-10-23 01:37:07,140 INFO     [main] [run:  47] Vega specification outputted as: spec.json
2017-10-23 01:43:59,263 INFO     [main] [<module>:  52] Starting Script
2017-10-23 01:43:59,264 INFO     [model] [build:  17] Building Vega Specification...
2017-10-23 01:43:59,264 INFO     [model] [build:  44] Done Building
2017-10-23 01:43:59,265 INFO     [main] [run:  47] Vega specification outputted as: spec.json
2017-10-23 01:50:41,203 INFO     [main] [<module>:  52] Starting Script
2017-10-23 01:50:41,204 INFO     [model] [build:  17] Building Vega Specification...
2017-10-23 01:50:41,205 ERROR    [main] [<module>:  88] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 85, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 42, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 24, in build
    data = json.loads(loaded_data)
  File "/Users/conder/anaconda/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/conder/anaconda/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 32 (char 31)

2017-10-23 01:50:41,205 INFO     [main] [<module>:  89] Ending Script Unsuccessfully
2017-10-23 01:52:13,181 INFO     [main] [<module>:  52] Starting Script
2017-10-23 01:52:13,182 INFO     [model] [build:  17] Building Vega Specification...
2017-10-23 01:52:13,182 INFO     [model] [build:  48] Done Building
2017-10-23 01:52:13,183 INFO     [main] [run:  47] Vega specification outputted as: spec.json
2017-10-23 01:53:24,567 INFO     [main] [<module>:  52] Starting Script
2017-10-23 01:53:24,568 INFO     [model] [build:  17] Building Vega Specification...
2017-10-23 01:53:24,569 ERROR    [main] [<module>:  88] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 85, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 42, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 19, in build
    skel_file = open('skeletons/barchart_simple.json').read()
FileNotFoundError: [Errno 2] No such file or directory: 'skeletons/barchart_simple.json'

2017-10-23 01:53:24,569 INFO     [main] [<module>:  89] Ending Script Unsuccessfully
2017-10-23 01:53:40,301 INFO     [main] [<module>:  52] Starting Script
2017-10-23 01:53:40,302 INFO     [model] [build:  17] Building Vega Specification...
2017-10-23 01:53:40,303 INFO     [model] [build:  48] Done Building
2017-10-23 01:53:40,304 INFO     [main] [run:  47] Vega specification outputted as: spec.json
2017-10-23 02:00:16,046 INFO     [main] [<module>:  52] Starting Script
2017-10-23 02:00:16,047 INFO     [model] [build:  24] Building Vega Specification...
2017-10-23 02:00:16,048 ERROR    [main] [<module>:  88] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 85, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 42, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 26, in build
    skel_file = open(Skeletons.BarChart).read()
TypeError: expected str, bytes or os.PathLike object, not Skeletons

2017-10-23 02:00:16,048 INFO     [main] [<module>:  89] Ending Script Unsuccessfully
2017-10-23 02:00:54,377 INFO     [main] [<module>:  52] Starting Script
2017-10-23 02:00:54,378 INFO     [model] [build:  24] Building Vega Specification...
2017-10-23 02:00:54,379 ERROR    [main] [<module>:  88] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 85, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 42, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 26, in build
    skel_file = open(str(Skeletons.BarChart)).read()
FileNotFoundError: [Errno 2] No such file or directory: 'Skeletons.BarChart'

2017-10-23 02:00:54,379 INFO     [main] [<module>:  89] Ending Script Unsuccessfully
2017-10-23 02:01:14,369 INFO     [main] [<module>:  52] Starting Script
2017-10-23 02:01:14,370 INFO     [model] [build:  24] Building Vega Specification...
2017-10-23 02:01:14,370 ERROR    [main] [<module>:  88] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 85, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 42, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 26, in build
    skel_file = open(Skeletons.BarChart).read()
TypeError: expected str, bytes or os.PathLike object, not Skeletons

2017-10-23 02:01:14,370 INFO     [main] [<module>:  89] Ending Script Unsuccessfully
2017-10-23 02:02:34,544 INFO     [main] [<module>:  52] Starting Script
2017-10-23 02:02:34,545 INFO     [model] [build:  27] Building Vega Specification...
2017-10-23 02:02:34,546 INFO     [model] [build:  58] Done Building
2017-10-23 02:02:34,546 INFO     [main] [run:  47] Vega specification outputted as: spec.json
2017-10-23 02:06:12,796 INFO     [main] [<module>:  52] Starting Script
2017-10-23 02:06:12,797 INFO     [model] [build:  27] Building Vega Specification...
2017-10-23 02:06:12,798 ERROR    [main] [<module>:  88] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 85, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 42, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 40, in build
    for idx, _ in enumerate(5):
TypeError: 'int' object is not iterable

2017-10-23 02:06:12,798 INFO     [main] [<module>:  89] Ending Script Unsuccessfully
2017-10-23 02:06:27,007 INFO     [main] [<module>:  52] Starting Script
2017-10-23 02:06:27,008 INFO     [model] [build:  27] Building Vega Specification...
2017-10-23 02:06:27,009 ERROR    [main] [<module>:  88] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 85, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 42, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 40, in build
    for idx, _ in range(5):
TypeError: 'int' object is not iterable

2017-10-23 02:06:27,009 INFO     [main] [<module>:  89] Ending Script Unsuccessfully
2017-10-23 02:06:58,755 INFO     [main] [<module>:  52] Starting Script
2017-10-23 02:06:58,757 INFO     [model] [build:  27] Building Vega Specification...
2017-10-23 02:06:58,758 ERROR    [main] [<module>:  88] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 85, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 42, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/auto_vega/model.py", line 40, in build
    for idx, _ in range(0, 5):
TypeError: 'int' object is not iterable

2017-10-23 02:06:58,758 INFO     [main] [<module>:  89] Ending Script Unsuccessfully
2017-10-23 02:07:11,044 INFO     [main] [<module>:  52] Starting Script
2017-10-23 02:07:11,045 INFO     [model] [build:  27] Building Vega Specification...
2017-10-23 02:07:11,046 INFO     [model] [build:  66] Done Building
2017-10-23 02:07:11,046 INFO     [main] [run:  47] Vega specification outputted as: spec.json
2017-10-23 02:08:02,586 INFO     [main] [<module>:  52] Starting Script
2017-10-23 02:08:02,587 INFO     [model] [build:  27] Building Vega Specification...
2017-10-23 02:08:02,588 INFO     [model] [build:  66] Done Building
2017-10-23 02:08:02,588 INFO     [main] [run:  47] Vega specification outputted as: spec.json
2017-10-23 02:57:59,671 INFO     [main] [<module>:  69] Starting Script
2017-10-23 02:57:59,673 ERROR    [main] [<module>: 105] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 102, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 42, in run
    data, columns = convert_csv_to_dict(data_file, columns)
NameError: name 'convert_csv_to_dict' is not defined

2017-10-23 02:57:59,673 INFO     [main] [<module>: 106] Ending Script Unsuccessfully
2017-10-23 02:58:32,715 INFO     [main] [<module>:  70] Starting Script
2017-10-23 02:58:32,717 ERROR    [main] [<module>: 106] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 103, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 58, in run
    data, columns = convert_csv_to_dict(data_file, columns)
NameError: name 'convert_csv_to_dict' is not defined

2017-10-23 02:58:32,717 INFO     [main] [<module>: 107] Ending Script Unsuccessfully
2017-10-23 02:59:28,543 INFO     [main] [<module>:  70] Starting Script
2017-10-23 02:59:28,545 ERROR    [main] [<module>: 106] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 103, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 58, in run
    data, columns = self.convert_csv_to_dict(data_file, columns)
  File "main.py", line 44, in convert_csv_to_dict
    for line in reader:
  File "/Users/conder/anaconda/lib/python3.6/csv.py", line 111, in __next__
    self.fieldnames
  File "/Users/conder/anaconda/lib/python3.6/csv.py", line 98, in fieldnames
    self._fieldnames = next(self.reader)
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)

2017-10-23 02:59:28,545 INFO     [main] [<module>: 107] Ending Script Unsuccessfully
2017-10-23 03:01:11,361 INFO     [main] [<module>:  70] Starting Script
2017-10-23 03:01:11,362 INFO     [model] [build:  27] Building Vega Specification...
2017-10-23 03:01:11,363 INFO     [model] [build:  43] Done Building
2017-10-23 03:01:11,364 INFO     [main] [run:  65] Vega specification outputted as: spec.json
2017-10-23 03:05:37,204 INFO     [main] [<module>:  70] Starting Script
2017-10-23 03:05:37,205 ERROR    [main] [<module>: 106] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 103, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 58, in run
    data, columns = self.convert_csv_to_dict(data_file, columns)
  File "main.py", line 45, in convert_csv_to_dict
    yield data.append({unicode(key, 'utf-8'):unicode(value, 'utf-8') for key, value in row.iteritems()})
NameError: name 'row' is not defined

2017-10-23 03:05:37,206 INFO     [main] [<module>: 107] Ending Script Unsuccessfully
2017-10-23 03:05:45,387 INFO     [main] [<module>:  70] Starting Script
2017-10-23 03:05:45,389 ERROR    [main] [<module>: 106] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 103, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 58, in run
    data, columns = self.convert_csv_to_dict(data_file, columns)
  File "main.py", line 45, in convert_csv_to_dict
    yield data.append({unicode(key, 'utf-8'):unicode(value, 'utf-8') for key, value in row.iteritems()})
AttributeError: 'collections.OrderedDict' object has no attribute 'iteritems'

2017-10-23 03:05:45,389 INFO     [main] [<module>: 107] Ending Script Unsuccessfully
2017-10-23 03:11:22,007 INFO     [main] [<module>:  64] Starting Script
2017-10-23 03:11:22,032 ERROR    [main] [<module>: 100] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 97, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 52, in run
    data, columns = self.convert_csv_to_dict(data_file, columns)
TypeError: 'NoneType' object is not iterable

2017-10-23 03:11:22,032 INFO     [main] [<module>: 101] Ending Script Unsuccessfully
2017-10-23 03:13:54,418 INFO     [main] [<module>:  64] Starting Script
2017-10-23 03:13:54,422 ERROR    [main] [<module>: 100] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 97, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 52, in run
    data, columns = self.convert_csv_to_dict(data_file, columns)
TypeError: 'NoneType' object is not iterable

2017-10-23 03:13:54,422 INFO     [main] [<module>: 101] Ending Script Unsuccessfully
2017-10-23 03:18:34,716 INFO     [main] [<module>:  70] Starting Script
2017-10-23 03:18:34,718 ERROR    [main] [<module>: 106] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 103, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 58, in run
    data, columns = self.convert_csv_to_dict(data_file, columns)
  File "main.py", line 45, in convert_csv_to_dict
    data.append({unicode(key, 'utf-8'):unicode(value, 'utf-8') for key, value in row.iteritems()})
NameError: name 'row' is not defined

2017-10-23 03:18:34,718 INFO     [main] [<module>: 107] Ending Script Unsuccessfully
2017-10-23 03:18:40,884 INFO     [main] [<module>:  70] Starting Script
2017-10-23 03:18:40,885 ERROR    [main] [<module>: 106] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 103, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 58, in run
    data, columns = self.convert_csv_to_dict(data_file, columns)
  File "main.py", line 45, in convert_csv_to_dict
    data.append({unicode(key, 'utf-8'):unicode(value, 'utf-8') for key, value in line.iteritems()})
AttributeError: 'collections.OrderedDict' object has no attribute 'iteritems'

2017-10-23 03:18:40,885 INFO     [main] [<module>: 107] Ending Script Unsuccessfully
2017-10-23 03:19:23,690 INFO     [main] [<module>:  70] Starting Script
2017-10-23 03:19:23,691 ERROR    [main] [<module>: 106] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 103, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 58, in run
    data, columns = self.convert_csv_to_dict(data_file, columns)
  File "main.py", line 45, in convert_csv_to_dict
    data.append({unicode(key, 'utf-8'):unicode(value, 'utf-8') for key, value in line.items()})
  File "main.py", line 45, in <dictcomp>
    data.append({unicode(key, 'utf-8'):unicode(value, 'utf-8') for key, value in line.items()})
NameError: name 'unicode' is not defined

2017-10-23 03:19:23,692 INFO     [main] [<module>: 107] Ending Script Unsuccessfully
2017-10-23 03:20:24,267 INFO     [main] [<module>:  70] Starting Script
2017-10-23 03:20:24,269 ERROR    [main] [<module>: 106] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 103, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 58, in run
    data, columns = self.convert_csv_to_dict(data_file, columns)
  File "main.py", line 45, in convert_csv_to_dict
    data.append({str(key, 'utf-8'):str(value, 'utf-8') for key, value in line.items()})
  File "main.py", line 45, in <dictcomp>
    data.append({str(key, 'utf-8'):str(value, 'utf-8') for key, value in line.items()})
TypeError: decoding str is not supported

2017-10-23 03:20:24,269 INFO     [main] [<module>: 107] Ending Script Unsuccessfully
2017-10-23 03:20:35,847 INFO     [main] [<module>:  70] Starting Script
2017-10-23 03:20:35,848 ERROR    [main] [<module>: 106] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 103, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 58, in run
    data, columns = self.convert_csv_to_dict(data_file, columns)
  File "main.py", line 45, in convert_csv_to_dict
    data.append({str.decode(key, 'utf-8'):str.decode(value, 'utf-8') for key, value in line.items()})
  File "main.py", line 45, in <dictcomp>
    data.append({str.decode(key, 'utf-8'):str.decode(value, 'utf-8') for key, value in line.items()})
AttributeError: type object 'str' has no attribute 'decode'

2017-10-23 03:20:35,848 INFO     [main] [<module>: 107] Ending Script Unsuccessfully
2017-10-23 03:21:16,339 INFO     [main] [<module>:  70] Starting Script
2017-10-23 03:21:16,341 INFO     [model] [build:  27] Building Vega Specification...
2017-10-23 03:21:16,341 INFO     [model] [build:  43] Done Building
2017-10-23 03:21:16,342 INFO     [main] [run:  65] Vega specification outputted as: spec.json
2017-10-23 03:21:31,185 INFO     [main] [<module>:  70] Starting Script
2017-10-23 03:21:31,187 INFO     [model] [build:  27] Building Vega Specification...
2017-10-23 03:21:31,187 INFO     [model] [build:  43] Done Building
2017-10-23 03:21:31,188 INFO     [main] [run:  65] Vega specification outputted as: spec.json
2017-10-23 03:23:01,925 INFO     [main] [<module>:  70] Starting Script
2017-10-23 03:23:01,937 ERROR    [main] [<module>: 106] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 103, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 58, in run
    data, columns = self.convert_csv_to_dict(data_file, columns)
  File "main.py", line 44, in convert_csv_to_dict
    for line in reader:
  File "/Users/conder/anaconda/lib/python3.6/csv.py", line 111, in __next__
    self.fieldnames
  File "/Users/conder/anaconda/lib/python3.6/csv.py", line 98, in fieldnames
    self._fieldnames = next(self.reader)
  File "/Users/conder/anaconda/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
  File "/Users/conder/anaconda/lib/python3.6/encodings/utf_16.py", line 67, in _buffer_decode
    raise UnicodeError("UTF-16 stream does not start with BOM")
UnicodeError: UTF-16 stream does not start with BOM

2017-10-23 03:23:01,937 INFO     [main] [<module>: 107] Ending Script Unsuccessfully
2017-10-23 03:23:29,298 INFO     [main] [<module>:  70] Starting Script
2017-10-23 03:23:29,308 ERROR    [main] [<module>: 106] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 103, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 58, in run
    data, columns = self.convert_csv_to_dict(data_file, columns)
  File "main.py", line 44, in convert_csv_to_dict
    for line in reader:
  File "/Users/conder/anaconda/lib/python3.6/csv.py", line 111, in __next__
    self.fieldnames
  File "/Users/conder/anaconda/lib/python3.6/csv.py", line 98, in fieldnames
    self._fieldnames = next(self.reader)
  File "/Users/conder/anaconda/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)

2017-10-23 03:23:29,308 INFO     [main] [<module>: 107] Ending Script Unsuccessfully
2017-10-23 03:24:06,401 INFO     [main] [<module>:  72] Starting Script
2017-10-23 03:24:06,403 ERROR    [main] [<module>: 108] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 105, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 60, in run
    data, columns = self.convert_csv_to_dict(data_file, columns)
  File "main.py", line 45, in convert_csv_to_dict
    line.strip('\ufeff\"')
AttributeError: 'collections.OrderedDict' object has no attribute 'strip'

2017-10-23 03:24:06,403 INFO     [main] [<module>: 109] Ending Script Unsuccessfully
2017-10-23 03:24:35,068 INFO     [main] [<module>:  73] Starting Script
2017-10-23 03:24:35,070 ERROR    [main] [<module>: 109] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 106, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 61, in run
    data, columns = self.convert_csv_to_dict(data_file, columns)
  File "main.py", line 46, in convert_csv_to_dict
    line.strip('\ufeff\"')
AttributeError: 'collections.OrderedDict' object has no attribute 'strip'

2017-10-23 03:24:35,070 INFO     [main] [<module>: 110] Ending Script Unsuccessfully
2017-10-23 03:24:48,322 INFO     [main] [<module>:  73] Starting Script
2017-10-23 03:24:48,324 INFO     [model] [build:  27] Building Vega Specification...
2017-10-23 03:24:48,325 INFO     [model] [build:  43] Done Building
2017-10-23 03:24:48,325 INFO     [main] [run:  68] Vega specification outputted as: spec.json
2017-10-23 03:26:07,571 INFO     [main] [<module>:  73] Starting Script
2017-10-23 03:26:07,578 INFO     [model] [build:  27] Building Vega Specification...
2017-10-23 03:26:07,579 INFO     [model] [build:  43] Done Building
2017-10-23 03:26:07,580 INFO     [main] [run:  68] Vega specification outputted as: spec.json
2017-10-23 03:27:01,067 INFO     [main] [<module>:  70] Starting Script
2017-10-23 03:27:01,069 INFO     [model] [build:  27] Building Vega Specification...
2017-10-23 03:27:01,070 INFO     [model] [build:  43] Done Building
2017-10-23 03:27:01,070 INFO     [main] [run:  65] Vega specification outputted as: spec.json
2017-10-23 03:29:24,936 INFO     [main] [<module>:  70] Starting Script
2017-10-23 03:29:24,938 ERROR    [main] [<module>: 106] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 103, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 58, in run
    data, columns = self.convert_csv_to_dict(data_file, columns)
  File "main.py", line 51, in convert_csv_to_dict
    for k, _ in data[0]:
ValueError: too many values to unpack (expected 2)

2017-10-23 03:29:24,938 INFO     [main] [<module>: 107] Ending Script Unsuccessfully
2017-10-23 03:29:57,614 INFO     [main] [<module>:  71] Starting Script
2017-10-23 03:29:57,616 INFO     [model] [build:  27] Building Vega Specification...
2017-10-23 03:29:57,616 ERROR    [main] [<module>: 107] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 104, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 61, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 38, in build
    val = self.columns[0]
TypeError: 'NoneType' object is not subscriptable

2017-10-23 03:29:57,616 INFO     [main] [<module>: 108] Ending Script Unsuccessfully
2017-10-23 03:31:27,734 INFO     [main] [<module>:  70] Starting Script
2017-10-23 03:31:27,735 INFO     [model] [build:  27] Building Vega Specification...
2017-10-23 03:31:27,736 INFO     [model] [build:  43] Done Building
2017-10-23 03:31:27,736 INFO     [main] [run:  65] Vega specification outputted as: spec.json
2017-10-23 03:31:48,162 INFO     [main] [<module>:  72] Starting Script
2017-10-23 03:31:48,165 INFO     [model] [build:  27] Building Vega Specification...
2017-10-23 03:31:48,165 INFO     [model] [build:  43] Done Building
2017-10-23 03:31:48,166 INFO     [main] [run:  67] Vega specification outputted as: spec.json
2017-10-23 03:39:16,042 INFO     [main] [<module>:  71] Starting Script
2017-10-23 03:39:16,043 INFO     [model] [build:  27] Building Vega Specification...
2017-10-23 03:39:16,044 INFO     [model] [build:  43] Done Building
2017-10-23 03:39:16,045 INFO     [main] [run:  66] Vega specification outputted as: spec.json
2017-10-23 03:46:18,194 INFO     [main] [<module>:  71] Starting Script
2017-10-23 03:46:18,199 INFO     [model] [build:  49] Building Vega Specification for a scatter plot...
2017-10-23 03:46:18,226 INFO     [model] [build:  67] Done Building
2017-10-23 03:46:18,238 INFO     [main] [run:  66] Vega specification outputted as: spec.json
2017-10-23 03:51:57,802 INFO     [main] [<module>:  73] Starting Script
2017-10-23 03:51:57,804 ERROR    [main] [<module>: 109] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 106, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 61, in run
    data, columns = self.convert_csv_to_dict(data_file, columns)
  File "main.py", line 46, in convert_csv_to_dict
    record[column] = line[column]
KeyError: 'HorsePower'

2017-10-23 03:51:57,804 INFO     [main] [<module>: 110] Ending Script Unsuccessfully
2017-10-23 03:52:17,657 INFO     [main] [<module>:  74] Starting Script
2017-10-23 03:52:17,659 ERROR    [main] [<module>: 110] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 107, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 62, in run
    data, columns = self.convert_csv_to_dict(data_file, columns)
  File "main.py", line 47, in convert_csv_to_dict
    record[column] = line[column]
KeyError: 'HorsePower'

2017-10-23 03:52:17,659 INFO     [main] [<module>: 111] Ending Script Unsuccessfully
2017-10-23 03:56:37,322 INFO     [main] [<module>:  73] Starting Script
2017-10-23 03:56:37,324 ERROR    [main] [<module>: 109] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 106, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 61, in run
    data, columns = self.convert_csv_to_dict(data_file, columns)
  File "main.py", line 41, in convert_csv_to_dict
    reader = dict(csv.DictReader(open(data_file, encoding='utf-8-sig')))
ValueError: dictionary update sequence element #0 has length 9; 2 is required

2017-10-23 03:56:37,324 INFO     [main] [<module>: 110] Ending Script Unsuccessfully
2017-10-23 03:57:47,611 INFO     [main] [<module>:  74] Starting Script
2017-10-23 03:57:47,613 ERROR    [main] [<module>: 110] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 107, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 62, in run
    data, columns = self.convert_csv_to_dict(data_file, columns)
  File "main.py", line 47, in convert_csv_to_dict
    record[column] = line[column]
KeyError: 'HorsePower'

2017-10-23 03:57:47,613 INFO     [main] [<module>: 111] Ending Script Unsuccessfully
2017-10-23 03:58:02,478 INFO     [main] [<module>:  74] Starting Script
2017-10-23 03:58:02,480 ERROR    [main] [<module>: 110] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 107, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 62, in run
    data, columns = self.convert_csv_to_dict(data_file, columns)
  File "main.py", line 47, in convert_csv_to_dict
    record[column] = dict_line[column]
KeyError: 'HorsePower'

2017-10-23 03:58:02,480 INFO     [main] [<module>: 111] Ending Script Unsuccessfully
2017-10-23 03:58:16,540 INFO     [main] [<module>:  75] Starting Script
2017-10-23 03:58:16,542 ERROR    [main] [<module>: 111] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 108, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 63, in run
    data, columns = self.convert_csv_to_dict(data_file, columns)
  File "main.py", line 48, in convert_csv_to_dict
    record[column] = dict_line[column]
KeyError: 'HorsePower'

2017-10-23 03:58:16,542 INFO     [main] [<module>: 112] Ending Script Unsuccessfully
2017-10-23 03:58:46,100 INFO     [main] [<module>:  75] Starting Script
2017-10-23 03:58:46,102 ERROR    [main] [<module>: 111] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 108, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 63, in run
    data, columns = self.convert_csv_to_dict(data_file, columns)
  File "main.py", line 49, in convert_csv_to_dict
    data.append(record)
NameError: name 'data' is not defined

2017-10-23 03:58:46,102 INFO     [main] [<module>: 112] Ending Script Unsuccessfully
2017-10-23 04:00:45,831 INFO     [main] [<module>:  78] Starting Script
2017-10-23 04:00:45,836 INFO     [model] [build:  49] Building Vega Specification for a scatter plot...
2017-10-23 04:00:45,848 INFO     [model] [build:  67] Done Building
2017-10-23 04:00:45,854 INFO     [main] [run:  73] Vega specification outputted as: spec.json
2017-10-23 04:03:59,417 INFO     [main] [<module>:  78] Starting Script
2017-10-23 04:03:59,423 INFO     [model] [build:  49] Building Vega Specification for a scatter plot...
2017-10-23 04:03:59,434 INFO     [model] [build:  67] Done Building
2017-10-23 04:03:59,439 INFO     [main] [run:  73] Vega specification outputted as: spec.json
2017-10-23 04:05:29,462 INFO     [main] [<module>:  78] Starting Script
2017-10-23 04:05:29,468 INFO     [model] [build:  49] Building Vega Specification for a scatter plot...
2017-10-23 04:05:29,480 INFO     [model] [build:  67] Done Building
2017-10-23 04:05:29,486 INFO     [main] [run:  73] Vega specification outputted as: spec.json
2017-10-23 04:06:07,464 INFO     [main] [<module>:  78] Starting Script
2017-10-23 04:06:07,471 INFO     [model] [build:  49] Building Vega Specification for a scatter plot...
2017-10-23 04:06:07,486 INFO     [model] [build:  67] Done Building
2017-10-23 04:06:07,491 INFO     [main] [run:  73] Vega specification outputted as: spec.json
2017-10-23 04:17:10,569 INFO     [main] [<module>:  78] Starting Script
2017-10-23 04:17:10,575 INFO     [model] [build:  49] Building Vega Specification for a scatter plot...
2017-10-23 04:17:10,579 ERROR    [main] [<module>: 114] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 111, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 68, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 61, in build
    elif idx % 3 == 2:
NameError: name 'idx' is not defined

2017-10-23 04:17:10,579 INFO     [main] [<module>: 115] Ending Script Unsuccessfully
2017-10-23 04:17:16,399 INFO     [main] [<module>:  78] Starting Script
2017-10-23 04:17:16,405 INFO     [model] [build:  49] Building Vega Specification for a scatter plot...
2017-10-23 04:17:16,417 INFO     [model] [build:  67] Done Building
2017-10-23 04:17:16,423 INFO     [main] [run:  73] Vega specification outputted as: spec.json
2017-10-23 04:18:14,092 INFO     [main] [<module>:  78] Starting Script
2017-10-23 04:18:14,098 INFO     [model] [build:  49] Building Vega Specification for a scatter plot...
2017-10-23 04:18:14,110 INFO     [model] [build:  67] Done Building
2017-10-23 04:18:14,116 INFO     [main] [run:  73] Vega specification outputted as: spec.json
2017-10-23 04:21:01,727 INFO     [main] [<module>:  78] Starting Script
2017-10-23 04:21:01,733 INFO     [model] [build:  49] Building Vega Specification for a scatter plot...
2017-10-23 04:21:01,745 INFO     [model] [build:  67] Done Building
2017-10-23 04:21:01,750 INFO     [main] [run:  73] Vega specification outputted as: spec.json
2017-10-23 04:31:54,279 INFO     [main] [<module>:  78] Starting Script
2017-10-23 04:31:54,284 INFO     [model] [build:  49] Building Vega Specification for a scatter plot...
2017-10-23 04:31:54,297 INFO     [model] [build:  67] Done Building
2017-10-23 04:31:54,304 INFO     [main] [run:  73] Vega specification outputted as: spec.json
2017-10-23 04:31:55,665 INFO     [main] [<module>:  78] Starting Script
2017-10-23 04:31:55,666 ERROR    [main] [<module>: 114] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 111, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 66, in run
    data, columns = self.convert_csv_to_dict(data_file, columns)
  File "main.py", line 41, in convert_csv_to_dict
    reader = csv.DictReader(open(data_file, encoding='utf-8-sig'))
FileNotFoundError: [Errno 2] No such file or directory: 'examples/example1_barchart.json'

2017-10-23 04:31:55,667 INFO     [main] [<module>: 115] Ending Script Unsuccessfully
2017-10-23 04:32:13,431 INFO     [main] [<module>:  78] Starting Script
2017-10-23 04:32:13,433 INFO     [model] [build:  27] Building Vega Specification for a bar chart...
2017-10-23 04:32:13,434 INFO     [model] [build:  43] Done Building
2017-10-23 04:32:13,434 INFO     [main] [run:  73] Vega specification outputted as: spec.json
2017-10-23 04:33:37,363 INFO     [main] [<module>:  78] Starting Script
2017-10-23 04:33:37,365 INFO     [model] [build:  27] Building Vega Specification for a bar chart...
2017-10-23 04:33:37,366 INFO     [model] [build:  43] Done Building
2017-10-23 04:33:37,366 INFO     [main] [run:  73] Vega specification outputted as: spec.json
2017-10-23 04:40:05,723 INFO     [main] [<module>:  78] Starting Script
2017-10-23 04:40:05,728 INFO     [model] [build:  49] Building Vega Specification for a scatter plot...
2017-10-23 04:40:05,740 INFO     [model] [build:  67] Done Building
2017-10-23 04:40:05,744 INFO     [main] [run:  73] Vega specification outputted as: spec.json
2017-10-23 18:03:13,460 INFO     [main] [<module>:  78] Starting Script
2017-10-23 18:03:13,467 INFO     [model] [build:  49] Building Vega Specification for a scatter plot...
2017-10-23 18:03:13,477 INFO     [model] [build:  67] Done Building
2017-10-23 18:03:13,481 INFO     [main] [run:  73] Vega specification outputted as: spec.json
2017-10-26 10:39:58,784 INFO     [main] [<module>:  83] Starting Script
2017-10-26 10:39:58,788 INFO     [model] [build:  32] Building Vega Specification for a bar chart...
2017-10-26 10:39:58,789 ERROR    [main] [<module>: 119] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 116, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 73, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 40, in build
    min_domain, max_domain = get_domain()
NameError: name 'get_domain' is not defined

2017-10-26 10:39:58,789 INFO     [main] [<module>: 120] Ending Script Unsuccessfully
2017-10-26 10:40:14,619 INFO     [main] [<module>:  83] Starting Script
2017-10-26 10:40:14,621 INFO     [model] [build:  32] Building Vega Specification for a bar chart...
2017-10-26 10:40:14,622 ERROR    [main] [<module>: 119] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 116, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 73, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 40, in build
    min_domain, max_domain = self.get_domain()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 65, in get_domain
    max_domain = max(max_domain, value)
TypeError: '>' not supported between instances of 'str' and 'float'

2017-10-26 10:40:14,623 INFO     [main] [<module>: 120] Ending Script Unsuccessfully
2017-10-26 10:40:38,492 INFO     [main] [<module>:  83] Starting Script
2017-10-26 10:40:38,493 INFO     [model] [build:  32] Building Vega Specification for a bar chart...
2017-10-26 10:40:38,495 ERROR    [main] [<module>: 119] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 116, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 73, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 40, in build
    min_domain, max_domain = self.get_domain()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 65, in get_domain
    max_domain = max(max_domain, float(value))
ValueError: could not convert string to float: 'amount'

2017-10-26 10:40:38,495 INFO     [main] [<module>: 120] Ending Script Unsuccessfully
2017-10-26 10:41:15,223 INFO     [main] [<module>:  83] Starting Script
2017-10-26 10:41:15,225 INFO     [model] [build:  32] Building Vega Specification for a bar chart...
2017-10-26 10:41:15,226 ERROR    [main] [<module>: 119] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 116, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 73, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 40, in build
    min_domain, max_domain = self.get_domain()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 66, in get_domain
    max_domain = max(max_domain, float(value))
ValueError: could not convert string to float: 'amount'

2017-10-26 10:41:15,226 INFO     [main] [<module>: 120] Ending Script Unsuccessfully
2017-10-26 10:42:04,710 INFO     [main] [<module>:  83] Starting Script
2017-10-26 10:42:04,712 INFO     [model] [build:  32] Building Vega Specification for a bar chart...
2017-10-26 10:42:04,713 ERROR    [main] [<module>: 119] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 116, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 73, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 40, in build
    min_domain, max_domain = self.get_domain()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 68, in get_domain
    max_domain = max(max_domain, float(value))
ValueError: could not convert string to float: 'amount'

2017-10-26 10:42:04,713 INFO     [main] [<module>: 120] Ending Script Unsuccessfully
2017-10-26 10:42:57,075 INFO     [main] [<module>:  83] Starting Script
2017-10-26 10:42:57,077 INFO     [model] [build:  32] Building Vega Specification for a bar chart...
2017-10-26 10:42:57,078 ERROR    [main] [<module>: 119] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 116, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 73, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 40, in build
    min_domain, max_domain = self.get_domain()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 65, in get_domain
    for key, value in record:
ValueError: too many values to unpack (expected 2)

2017-10-26 10:42:57,078 INFO     [main] [<module>: 120] Ending Script Unsuccessfully
2017-10-26 10:43:27,006 INFO     [main] [<module>:  83] Starting Script
2017-10-26 10:43:27,008 INFO     [model] [build:  32] Building Vega Specification for a bar chart...
2017-10-26 10:43:27,010 ERROR    [main] [<module>: 119] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 116, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 73, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 40, in build
    min_domain, max_domain = self.get_domain()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 66, in get_domain
    for key, value in record:
ValueError: too many values to unpack (expected 2)

2017-10-26 10:43:27,010 INFO     [main] [<module>: 120] Ending Script Unsuccessfully
2017-10-26 10:50:38,757 INFO     [main] [<module>:  83] Starting Script
2017-10-26 10:50:38,759 INFO     [model] [build:  32] Building Vega Specification for a bar chart...
2017-10-26 10:50:38,759 INFO     [model] [build:  48] Done Building
2017-10-26 10:50:38,760 INFO     [main] [run:  78] Vega specification outputted as: spec.json
2017-10-26 11:15:30,487 INFO     [main] [<module>:  83] Starting Script
2017-10-26 11:15:30,493 INFO     [model] [build:  57] Building Vega Specification for a scatter plot...
2017-10-26 11:15:30,494 ERROR    [main] [<module>: 119] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 116, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 73, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 65, in build
    min_domain, max_domain = self.get_domain()
TypeError: 'NoneType' object is not iterable

2017-10-26 11:15:30,495 INFO     [main] [<module>: 120] Ending Script Unsuccessfully
2017-10-26 11:18:03,799 INFO     [main] [<module>:  83] Starting Script
2017-10-26 11:18:03,805 INFO     [model] [build:  75] Building Vega Specification for a scatter plot...
2017-10-26 11:18:03,806 ERROR    [main] [<module>: 119] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 116, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 73, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 83, in build
    min_domain, max_domain = get_domain()
NameError: name 'get_domain' is not defined

2017-10-26 11:18:03,806 INFO     [main] [<module>: 120] Ending Script Unsuccessfully
2017-10-26 11:18:13,627 INFO     [main] [<module>:  83] Starting Script
2017-10-26 11:18:13,633 INFO     [model] [build:  75] Building Vega Specification for a scatter plot...
2017-10-26 11:18:13,634 ERROR    [main] [<module>: 119] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 116, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 73, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 83, in build
    min_domain, max_domain = self.get_domain()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 64, in get_domain
    for key, value in record:
ValueError: too many values to unpack (expected 2)

2017-10-26 11:18:13,634 INFO     [main] [<module>: 120] Ending Script Unsuccessfully
2017-10-26 11:19:29,768 INFO     [main] [<module>:  83] Starting Script
2017-10-26 11:19:29,775 INFO     [model] [build:  76] Building Vega Specification for a scatter plot...
2017-10-26 11:19:29,776 ERROR    [main] [<module>: 119] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 116, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 73, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 84, in build
    min_domain, max_domain = self.get_domain()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 67, in get_domain
    if key == x_title:
NameError: name 'key' is not defined

2017-10-26 11:19:29,776 INFO     [main] [<module>: 120] Ending Script Unsuccessfully
2017-10-26 11:20:20,068 INFO     [main] [<module>:  83] Starting Script
2017-10-26 11:20:20,074 INFO     [model] [build:  75] Building Vega Specification for a scatter plot...
2017-10-26 11:20:20,075 ERROR    [main] [<module>: 119] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 116, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 73, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 83, in build
    min_domain, max_domain = self.get_domain()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 67, in get_domain
    max_domain = max(max_domain, float(value))
ValueError: could not convert string to float: 'null'

2017-10-26 11:20:20,075 INFO     [main] [<module>: 120] Ending Script Unsuccessfully
2017-10-26 11:21:10,925 INFO     [main] [<module>:  83] Starting Script
2017-10-26 11:21:10,931 INFO     [model] [build:  74] Building Vega Specification for a scatter plot...
2017-10-26 11:21:10,932 ERROR    [main] [<module>: 119] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 116, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 73, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 82, in build
    min_domain, max_domain = self.get_domain()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 66, in get_domain
    max_domain = max(max_domain, float(value))
ValueError: could not convert string to float: 'null'

2017-10-26 11:21:10,932 INFO     [main] [<module>: 120] Ending Script Unsuccessfully
2017-10-26 11:21:48,466 INFO     [main] [<module>:  83] Starting Script
2017-10-26 11:21:48,472 INFO     [model] [build:  74] Building Vega Specification for a scatter plot...
2017-10-26 11:21:48,473 ERROR    [main] [<module>: 119] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 116, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 73, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 82, in build
    min_domain, max_domain = self.get_domain()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 66, in get_domain
    max_domain = max(max_domain, float(value))
ValueError: could not convert string to float: 'null'

2017-10-26 11:21:48,473 INFO     [main] [<module>: 120] Ending Script Unsuccessfully
2017-10-26 11:22:13,146 INFO     [main] [<module>:  83] Starting Script
2017-10-26 11:22:13,151 INFO     [model] [build:  74] Building Vega Specification for a scatter plot...
2017-10-26 11:22:13,152 ERROR    [main] [<module>: 119] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 116, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 73, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 82, in build
    min_domain, max_domain = self.get_domain()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 66, in get_domain
    max_domain = max(max_domain, float(value))
ValueError: could not convert string to float: 'null'

2017-10-26 11:22:13,152 INFO     [main] [<module>: 120] Ending Script Unsuccessfully
2017-10-26 11:22:35,290 INFO     [main] [<module>:  83] Starting Script
2017-10-26 11:22:35,296 INFO     [model] [build:  74] Building Vega Specification for a scatter plot...
2017-10-26 11:22:35,297 ERROR    [main] [<module>: 119] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 116, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 73, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 82, in build
    min_domain, max_domain = self.get_domain()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 66, in get_domain
    max_domain = max(max_domain, float(value))
ValueError: could not convert string to float: 'null'

2017-10-26 11:22:35,297 INFO     [main] [<module>: 120] Ending Script Unsuccessfully
2017-10-26 11:23:14,141 INFO     [main] [<module>:  83] Starting Script
2017-10-26 11:23:14,147 INFO     [model] [build:  74] Building Vega Specification for a scatter plot...
2017-10-26 11:23:14,175 INFO     [model] [build:  96] Done Building
2017-10-26 11:23:14,180 INFO     [main] [run:  78] Vega specification outputted as: spec.json
2017-10-26 11:26:17,084 INFO     [main] [<module>:  83] Starting Script
2017-10-26 11:26:17,090 INFO     [model] [build:  71] Building Vega Specification for a scatter plot...
2017-10-26 11:26:17,092 INFO     [model] [build:  93] Done Building
2017-10-26 11:26:17,092 INFO     [main] [run:  78] Vega specification outputted as: spec.json
2017-10-26 11:26:42,448 INFO     [main] [<module>:  83] Starting Script
2017-10-26 11:26:42,454 INFO     [model] [build:  71] Building Vega Specification for a scatter plot...
2017-10-26 11:26:42,466 INFO     [model] [build:  93] Done Building
2017-10-26 11:26:42,472 INFO     [main] [run:  78] Vega specification outputted as: spec.json
2017-10-26 11:35:47,617 INFO     [main] [<module>:  83] Starting Script
2017-10-26 11:35:47,621 INFO     [model] [build:  75] Building Vega Specification for a scatter plot...
2017-10-26 11:35:47,622 ERROR    [main] [<module>: 119] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 116, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 73, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 83, in build
    x_max_domain, y_high_range = self.get_domain()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 70, in get_domain
    heappush(y_data, value)
NameError: name 'heappush' is not defined

2017-10-26 11:35:47,622 INFO     [main] [<module>: 120] Ending Script Unsuccessfully
2017-10-26 11:36:08,932 INFO     [main] [<module>:  83] Starting Script
2017-10-26 11:36:08,937 INFO     [model] [build:  76] Building Vega Specification for a scatter plot...
2017-10-26 11:36:08,938 ERROR    [main] [<module>: 119] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 116, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 73, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 84, in build
    x_max_domain, y_high_range = self.get_domain()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 71, in get_domain
    heappush(y_data, value)
NameError: name 'heappush' is not defined

2017-10-26 11:36:08,938 INFO     [main] [<module>: 120] Ending Script Unsuccessfully
2017-10-26 11:36:27,828 INFO     [main] [<module>:  83] Starting Script
2017-10-26 11:36:27,833 INFO     [model] [build:  76] Building Vega Specification for a scatter plot...
2017-10-26 11:36:27,845 ERROR    [main] [<module>: 119] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 116, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 73, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 84, in build
    x_max_domain, y_high_range = self.get_domain()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 73, in get_domain
    return x_max_domain, np.percentile(y_data, 75)
  File "/Users/conder/anaconda/lib/python3.6/site-packages/numpy/lib/function_base.py", line 4116, in percentile
    interpolation=interpolation)
  File "/Users/conder/anaconda/lib/python3.6/site-packages/numpy/lib/function_base.py", line 3858, in _ureduce
    r = func(a, **kwargs)
  File "/Users/conder/anaconda/lib/python3.6/site-packages/numpy/lib/function_base.py", line 4233, in _percentile
    x1 = take(ap, indices_below, axis=axis) * weights_below
TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')

2017-10-26 11:36:27,845 INFO     [main] [<module>: 120] Ending Script Unsuccessfully
2017-10-26 11:36:50,904 INFO     [main] [<module>:  83] Starting Script
2017-10-26 11:36:50,909 INFO     [model] [build:  76] Building Vega Specification for a scatter plot...
2017-10-26 11:36:50,931 INFO     [model] [build: 100] Done Building
2017-10-26 11:36:50,936 INFO     [main] [run:  78] Vega specification outputted as: spec.json
2017-10-26 11:37:11,275 INFO     [main] [<module>:  83] Starting Script
2017-10-26 11:37:11,280 INFO     [model] [build:  76] Building Vega Specification for a scatter plot...
2017-10-26 11:37:11,293 INFO     [model] [build: 100] Done Building
2017-10-26 11:37:11,298 INFO     [main] [run:  78] Vega specification outputted as: spec.json
2017-10-26 11:37:36,817 INFO     [main] [<module>:  83] Starting Script
2017-10-26 11:37:36,822 INFO     [model] [build:  76] Building Vega Specification for a scatter plot...
2017-10-26 11:37:36,833 INFO     [model] [build: 100] Done Building
2017-10-26 11:37:36,837 INFO     [main] [run:  78] Vega specification outputted as: spec.json
2017-10-26 11:37:57,728 INFO     [main] [<module>:  83] Starting Script
2017-10-26 11:37:57,733 INFO     [model] [build:  76] Building Vega Specification for a scatter plot...
2017-10-26 11:37:57,747 INFO     [model] [build: 100] Done Building
2017-10-26 11:37:57,752 INFO     [main] [run:  78] Vega specification outputted as: spec.json
2017-10-26 11:38:15,372 INFO     [main] [<module>:  83] Starting Script
2017-10-26 11:38:15,377 INFO     [model] [build:  76] Building Vega Specification for a scatter plot...
2017-10-26 11:38:15,391 INFO     [model] [build: 100] Done Building
2017-10-26 11:38:15,396 INFO     [main] [run:  78] Vega specification outputted as: spec.json
2017-10-26 11:40:27,394 INFO     [main] [<module>:  83] Starting Script
2017-10-26 11:40:27,400 INFO     [model] [build:  74] Building Vega Specification for a scatter plot...
2017-10-26 11:40:27,412 INFO     [model] [build:  98] Done Building
2017-10-26 11:40:27,418 INFO     [main] [run:  78] Vega specification outputted as: spec.json
2017-10-26 11:57:05,206 INFO     [main] [<module>:  83] Starting Script
2017-10-26 11:57:05,214 INFO     [model] [build:  74] Building Vega Specification for a scatter plot...
2017-10-26 11:57:05,215 ERROR    [main] [<module>: 119] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 116, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 73, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 85, in build
    fill_new_values = [self.data, x_domain, y_domain, column[0], column[1], column[2]]
NameError: name 'column' is not defined

2017-10-26 11:57:05,215 INFO     [main] [<module>: 120] Ending Script Unsuccessfully
2017-10-26 11:57:36,691 INFO     [main] [<module>:  83] Starting Script
2017-10-26 11:57:36,698 INFO     [model] [build:  74] Building Vega Specification for a scatter plot...
2017-10-26 11:57:36,707 INFO     [model] [build:  90] Done Building
2017-10-26 11:57:36,715 INFO     [main] [run:  78] Vega specification outputted as: spec.json
2017-10-26 12:00:31,698 INFO     [main] [<module>:  83] Starting Script
2017-10-26 12:00:31,703 INFO     [model] [build:  32] Building Vega Specification for a bar chart...
2017-10-26 12:00:31,705 INFO     [model] [build:  51] Done Building
2017-10-26 12:00:31,706 INFO     [main] [run:  78] Vega specification outputted as: spec.json
2017-10-26 12:03:03,779 INFO     [main] [<module>:  83] Starting Script
2017-10-26 12:03:03,781 INFO     [model] [build:  40] Building Vega Specification for a bar chart...
2017-10-26 12:03:03,782 ERROR    [main] [<module>: 119] [Unknown Error] Traceback (most recent call last):
  File "main.py", line 116, in <module>
    chart_type = args.chart_type,)
  File "main.py", line 73, in run
    self.vega_json = self.chart.build()
  File "/Users/conder/Desktop/alphaclean_interface/generate_static/model.py", line 48, in build
    return self.update_data(self, data_fields, new_values)
TypeError: update_data() takes 3 positional arguments but 4 were given

2017-10-26 12:03:03,783 INFO     [main] [<module>: 120] Ending Script Unsuccessfully
2017-10-26 12:03:15,042 INFO     [main] [<module>:  83] Starting Script
2017-10-26 12:03:15,043 INFO     [model] [build:  40] Building Vega Specification for a bar chart...
2017-10-26 12:03:15,045 INFO     [model] [update_data:  33] Done Building
2017-10-26 12:03:15,045 INFO     [main] [run:  78] Vega specification outputted as: spec.json
2017-10-26 12:03:30,032 INFO     [main] [<module>:  83] Starting Script
2017-10-26 12:03:30,037 INFO     [model] [build:  71] Building Vega Specification for a scatter plot...
2017-10-26 12:03:30,043 INFO     [model] [update_data:  33] Done Building
2017-10-26 12:03:30,048 INFO     [main] [run:  78] Vega specification outputted as: spec.json
